### ISSUE TITLE
標準ライブラリになく外部クレート使うほどでもないパーツを共通化したい

### ISSUE THREAD

**Issue by laysakura** [yuk1ty/learning-systems-programming-in-rust#39]
https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/38#issuecomment-830697268 にて「GoのMultiWriter相当は少なくとも2つ以上の問題で出てきて共通化したい」という話をしました。

それ以外にも [雑mktemp](https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/29/files#diff-6cedb5df9f7ba09547b5c6f8f435e38fc5e499c902068a88759aae0a41c797cbR12-R21) なんかは少なくとも私は複数の問題で使いたいと思っています。

---

このリポジトリのトップレベルに `lspir-lib` libクレート ( lspir <- learning-systems-programing-in-rust )（名前は世の中のクレートと被らない限りこだわりありません）でも作り、その中に共通パーツを配置するのはいかがでしょう？

**Comment by yuk1ty** [comment]
レビューしている最中にもいくつか共通で使用できそうな箇所（たとえばエラー型とか）を見つけていて、`lib` クレートを導入するのを検討していて、ちょうどいいタイミングでした！ありがとうございます。作っちゃおうと思っています。

**Comment by laysakura** [comment]
ありがとうございます。でしたらこのissueに紐づけて作っていただければレビューで目を通させていただきます。

**Comment by laysakura** [comment]
#47 で対応されたのでclose
