### ISSUE TITLE
コンパイル時にwarningがあるときはCIをfailにしたい

### ISSUE THREAD

**Issue by laysakura** [yuk1ty/learning-systems-programming-in-rust#55]
https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/35#discussion_r625684605
このあたりのをCIで防ぎたい。

```bash
% RUSTFLAGS='-D warnings' cargo build --all-targets --all-features
```

でできるはず。

**Comment by laysakura** [comment]
`learning-systems-programming-in-rust/chapterN` のようなcrateのディレクトリで

```bash
cargo rustc -- -D warnings
```

とすればexist statusがnon-0になるが、 https://github.com/yuk1ty/learning-systems-programming-in-rust/issues/42 でcrateの構成も変わる可能性あるので、CIで自動化しておくとその作業のときに面倒。

**Comment by laysakura** [comment]
```bash
% cargo build --all-targets --all-features 2>&1 |grep -E '^warning: [0-9]* warnings emitted$'
```

で検知もできるが、cargo buildのhuman readableな出力が今後変わらない保証はないし、汚い。

**Comment by yuk1ty** [comment]
導入しましょう！

意図的に警告をスルーしたい場合は `allow` attribute を明示的に書いてもらうという運用で十分そうですしね。
